on: push
name: Demo pulumi

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1
      - name: Install Pulumi CLI
        uses: pulumi/actions@v4
      - name: Run Pulumi Up
        env: 
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        run: |
          op run --env-file .env -- pulumi stack select dev
          op run --env-file .env -- pulumi up --yes